version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: izhGet_bot
    restart: unless-stopped
    depends_on:
      - xray
    env_file:
      - .env
    volumes:
      # Сохранение базы данных
      - ./izhGet.db:/izhget_bot/izhGet.db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  xray:
    image: teddysun/xray:latest
    container_name: xray_proxy
    ports:
      - "1080:1080"
    volumes:
      - ./xray-config.json:/etc/xray/config.json
    restart: always
