from aiogram.types import InlineKeyboardMarkup, InlineKeyboardButton

inline_kb_time = InlineKeyboardMarkup(row_width=3)
inline_kb_time.row(InlineKeyboardButton('30 мин.', callback_data='time30'),
                   InlineKeyboardButton('60 мин.', callback_data='time60'),
                   InlineKeyboardButton('90 мин.', callback_data='time90'))

inline_kb_route = InlineKeyboardMarkup(row_width=3)
inline_kb_route.row(InlineKeyboardButton('1', callback_data='route1'),
                    InlineKeyboardButton('10', callback_data='route10'),
                    InlineKeyboardButton('11', callback_data='route11'))
inline_kb_route.row(InlineKeyboardButton('12', callback_data='route12'),
                    InlineKeyboardButton('2', callback_data='route2'),
                    InlineKeyboardButton('3', callback_data='route3'))
inline_kb_route.row(InlineKeyboardButton('4', callback_data='route4'),
                    InlineKeyboardButton('5', callback_data='route5'),
                    InlineKeyboardButton('7', callback_data='route7'))
inline_kb_route.row(InlineKeyboardButton('8', callback_data='route8'),
                    InlineKeyboardButton('9', callback_data='route9'),
                    InlineKeyboardButton('Все', callback_data='route0'), )

inline_40 = InlineKeyboardButton('Банк «Зенит»', callback_data='40')
inline_37 = InlineKeyboardButton('Больница', callback_data='37')
inline_26 = InlineKeyboardButton('Буммаш', callback_data='26')
inline_9 = InlineKeyboardButton('Воткинская линия', callback_data='9')
inline_50 = InlineKeyboardButton('Дом Дружбы народов', callback_data='50')
inline_2 = InlineKeyboardButton('Железнодорожный вокзал', callback_data='2')
inline_3 = InlineKeyboardButton('Завод мин.вод', callback_data='3')
inline_21 = InlineKeyboardButton('Зоопарк', callback_data='21')
inline_67 = InlineKeyboardButton('Италмас', callback_data='67')
inline_68 = InlineKeyboardButton('Карлутская набережная', callback_data='68')
inline_17 = InlineKeyboardButton('Магазин «Океан»', callback_data='17')
inline_52 = InlineKeyboardButton('Международный университет', callback_data='52')
inline_62 = InlineKeyboardButton('Молдавская', callback_data='62')
inline_18 = InlineKeyboardButton('Монтажный техникум', callback_data='18')
inline_20 = InlineKeyboardButton('Парк им.Кирова', callback_data='28')
inline_33 = InlineKeyboardButton('Пер. Воткинский', callback_data='33')
inline_10 = InlineKeyboardButton('Пер. Октябрьский', callback_data='10')
inline_34 = InlineKeyboardButton('Пер. Профсоюзный', callback_data='34')
inline_32 = InlineKeyboardButton('Пер. Уральский', callback_data='32')
inline_16 = InlineKeyboardButton('Пер. Широкий', callback_data='16')
inline_29 = InlineKeyboardButton('Покровская церковь', callback_data='29')
inline_61 = InlineKeyboardButton('Проспект Калашникова', callback_data='61')
inline_55 = InlineKeyboardButton('Радио “Адам”', callback_data='55')
inline_38 = InlineKeyboardButton('Речка Карлутка', callback_data='38')
inline_14 = InlineKeyboardButton('Свято-Михайловский собор', callback_data='14')
inline_27 = InlineKeyboardButton('Северный рынок', callback_data='27')
inline_19 = InlineKeyboardButton('Сельхозакадемия', callback_data='19')
inline_25 = InlineKeyboardButton('Сквер металлургов', callback_data='25')
inline_8 = InlineKeyboardButton('Трамвайное депо', callback_data='8')
inline_22 = InlineKeyboardButton('Ул. 30 лет Победы', callback_data='22')
inline_63 = InlineKeyboardButton('Ул. 40 лет Победы', callback_data='63')
inline_23 = InlineKeyboardButton('Ул. 6-я Подлесная', callback_data='23')
inline_24 = InlineKeyboardButton('Ул. 9-я Подлесная', callback_data='24')
inline_64 = InlineKeyboardButton('Ул. Бабушкина', callback_data='64')
inline_43 = InlineKeyboardButton('Ул. Братская', callback_data='43')
inline_39 = InlineKeyboardButton('Ул. Воровского', callback_data='39')
inline_59 = InlineKeyboardButton('Ул. Ворошилова', callback_data='59')
inline_4 = InlineKeyboardButton('Ул. Гагарина', callback_data='4')
inline_35 = InlineKeyboardButton('Ул. Герцена', callback_data='35')
inline_46 = InlineKeyboardButton('Ул. Загородная', callback_data='46')
inline_11 = InlineKeyboardButton('Ул. К.Либкнехта', callback_data='11')
inline_45 = InlineKeyboardButton('Ул. Кирпичная', callback_data='45')
inline_53 = InlineKeyboardButton('Ул. Коммунаров', callback_data='53')
inline_51 = InlineKeyboardButton('Ул. Краева', callback_data='51')
inline_41 = InlineKeyboardButton('Ул. Красноармейская', callback_data='41')
inline_56 = InlineKeyboardButton('Ул. Л.Толстого', callback_data='56')
inline_7 = InlineKeyboardButton('Ул. Магистральная', callback_data='7')
inline_47 = InlineKeyboardButton('Ул. Можарова', callback_data='47')
inline_1 = InlineKeyboardButton('Ул. Московская', callback_data='1')
inline_48 = InlineKeyboardButton('Ул. Огнеупорная', callback_data='48')
inline_65 = InlineKeyboardButton('Ул. Орджоникидзе', callback_data='65')
inline_58 = InlineKeyboardButton('Ул. Промышленная', callback_data='58')
inline_60 = InlineKeyboardButton('Ул. Т.Барамзиной', callback_data='60')
inline_30 = InlineKeyboardButton('Ул. Тимирязева', callback_data='30')
inline_54 = InlineKeyboardButton('Ул. Удмуртская', callback_data='54')
inline_36 = InlineKeyboardButton('ул. Халтурина-Реабилитационный центр “Адели”', callback_data='36')
inline_57 = InlineKeyboardButton('Ул. Шишкина', callback_data='57')
inline_5 = InlineKeyboardButton('Хозяйственная база', callback_data='5')
inline_66 = InlineKeyboardButton('Центр', callback_data='66')
inline_12 = InlineKeyboardButton('Центральная мечеть', callback_data='12')
inline_15 = InlineKeyboardButton('Центральный универмаг', callback_data='15')
inline_31 = InlineKeyboardButton('Школа № 64', callback_data='31')
inline_28 = InlineKeyboardButton('Школа № 79', callback_data='28')
inline_6 = InlineKeyboardButton('Южная автостанция', callback_data='6')
inline_44 = InlineKeyboardButton('Южный рынок', callback_data='44')
inline_13 = InlineKeyboardButton('Центр (сев.)', callback_data='13')
inline_42 = InlineKeyboardButton('Центр (вост.)', callback_data='42')
inline_49 = InlineKeyboardButton('Центр (южн.)', callback_data='49')

inline_kb0 = InlineKeyboardMarkup(row_width=2)
inline_kb0.row(inline_40, inline_37)
inline_kb0.row(inline_26, inline_9)
inline_kb0.row(inline_50, inline_2)
inline_kb0.row(inline_3, inline_21)
inline_kb0.row(inline_67, inline_68)
inline_kb0.row(inline_17, inline_52)
inline_kb0.row(inline_62, inline_18)
inline_kb0.row(inline_20, inline_33)
inline_kb0.row(inline_10, inline_34)
inline_kb0.row(inline_32, inline_16)
inline_kb0.row(inline_29, inline_61)
inline_kb0.row(inline_55, inline_38)
inline_kb0.row(inline_14, inline_27)
inline_kb0.row(inline_19, inline_25)
inline_kb0.row(inline_8, inline_22)
inline_kb0.row(inline_63, inline_23)
inline_kb0.row(inline_24, inline_64)
inline_kb0.row(inline_43, inline_39)
inline_kb0.row(inline_59, inline_4)
inline_kb0.row(inline_35, inline_46)
inline_kb0.row(inline_11, inline_45)
inline_kb0.row(inline_53, inline_51)
inline_kb0.row(inline_41, inline_56)
inline_kb0.row(inline_7, inline_47)
inline_kb0.row(inline_1, inline_48)
inline_kb0.row(inline_65, inline_58)
inline_kb0.row(inline_60, inline_30)
inline_kb0.row(inline_54, inline_57)
inline_kb0.row(inline_36)
inline_kb0.row(inline_5, inline_66)
inline_kb0.row(inline_12, inline_15)
inline_kb0.row(inline_31, inline_28)
inline_kb0.row(inline_6, inline_44)

inline_kb1 = InlineKeyboardMarkup(row_width=2)
inline_kb1.row(inline_9, inline_2)
inline_kb1.row(inline_3, inline_21)
inline_kb1.row(inline_17, inline_18)
inline_kb1.row(inline_20, inline_10)
inline_kb1.row(inline_16, inline_14)
inline_kb1.row(inline_19, inline_25)
inline_kb1.row(inline_8, inline_22)
inline_kb1.row(inline_23, inline_24)
inline_kb1.row(inline_4, inline_11)
inline_kb1.row(inline_7, inline_1)
inline_kb1.row(inline_5, inline_66)
inline_kb1.row(inline_12, inline_15)
inline_kb1.row(inline_6)

inline_kb10 = InlineKeyboardMarkup(row_width=2)
inline_kb10.row(inline_40, inline_37)
inline_kb10.row(inline_21, inline_67)
inline_kb10.row(inline_17, inline_62)
inline_kb10.row(inline_18, inline_20)
inline_kb10.row(inline_16, inline_61)
inline_kb10.row(inline_38, inline_14)
inline_kb10.row(inline_19, inline_25)
inline_kb10.row(inline_22, inline_63)
inline_kb10.row(inline_23, inline_24)
inline_kb10.row(inline_64, inline_39)
inline_kb10.row(inline_59, inline_41)
inline_kb10.row(inline_60, inline_66)
inline_kb10.row(inline_15)
inline_kb10.row(inline_36)

inline_kb11 = InlineKeyboardMarkup(row_width=2)
inline_kb11.row(inline_37, inline_50)
inline_kb11.row(inline_67, inline_68)
inline_kb11.row(inline_62, inline_61)
inline_kb11.row(inline_38, inline_58)
inline_kb11.row(inline_63, inline_64)
inline_kb11.row(inline_59, inline_51)
inline_kb11.row(inline_65, inline_58)
inline_kb11.row(inline_60, inline_66)
inline_kb11.row(inline_36)

inline_kb12 = InlineKeyboardMarkup(row_width=2)
inline_kb12.row(inline_40, inline_37)
inline_kb12.row(inline_9, inline_2)
inline_kb12.row(inline_3, inline_67)
inline_kb12.row(inline_62, inline_10)
inline_kb12.row(inline_61, inline_38)
inline_kb12.row(inline_8, inline_63)
inline_kb12.row(inline_64, inline_39)
inline_kb12.row(inline_59, inline_4)
inline_kb12.row(inline_11, inline_41)
inline_kb12.row(inline_7, inline_1)
inline_kb12.row(inline_60, inline_5)
inline_kb12.row(inline_66, inline_12)
inline_kb12.row(inline_6)
inline_kb12.row(inline_36)

inline_kb2 = InlineKeyboardMarkup(row_width=2)
inline_kb2.row(inline_40, inline_26)
inline_kb2.row(inline_50, inline_68)
inline_kb2.row(inline_17, inline_52)
inline_kb2.row(inline_16, inline_29)
inline_kb2.row(inline_55, inline_14)
inline_kb2.row(inline_27, inline_58)
inline_kb2.row(inline_39, inline_53)
inline_kb2.row(inline_51, inline_41)
inline_kb2.row(inline_56, inline_65)
inline_kb2.row(inline_58, inline_30)
inline_kb2.row(inline_54, inline_57)
inline_kb2.row(inline_66, inline_15)
inline_kb2.row(inline_28)

inline_kb3 = InlineKeyboardMarkup(row_width=2)
inline_kb3.row(inline_40, inline_9)
inline_kb3.row(inline_50, inline_2)
inline_kb3.row(inline_3, inline_10)
inline_kb3.row(inline_8, inline_58)
inline_kb3.row(inline_39, inline_4)
inline_kb3.row(inline_11, inline_51)
inline_kb3.row(inline_41, inline_7)
inline_kb3.row(inline_1, inline_65)
inline_kb3.row(inline_58, inline_5)
inline_kb3.row(inline_66, inline_12)
inline_kb3.row(inline_6)

inline_kb4 = InlineKeyboardMarkup(row_width=2)
inline_kb4.row(inline_40, inline_50)
inline_kb4.row(inline_21, inline_68)
inline_kb4.row(inline_17, inline_18)
inline_kb4.row(inline_20, inline_16)
inline_kb4.row(inline_14, inline_19)
inline_kb4.row(inline_25, inline_58)
inline_kb4.row(inline_22, inline_23)
inline_kb4.row(inline_24, inline_39)
inline_kb4.row(inline_51, inline_41)
inline_kb4.row(inline_65, inline_58)
inline_kb4.row(inline_66, inline_15)

inline_kb5 = InlineKeyboardMarkup(row_width=2)
inline_kb5.row(inline_40, inline_37)
inline_kb5.row(inline_26, inline_9)
inline_kb5.row(inline_33, inline_10)
inline_kb5.row(inline_34, inline_32)
inline_kb5.row(inline_29, inline_38)
inline_kb5.row(inline_27, inline_8)
inline_kb5.row(inline_43, inline_39)
inline_kb5.row(inline_4, inline_35)
inline_kb5.row(inline_46, inline_11)
inline_kb5.row(inline_45, inline_41)
inline_kb5.row(inline_7, inline_47)
inline_kb5.row(inline_48, inline_30)
inline_kb5.row(inline_5, inline_66)
inline_kb5.row(inline_12, inline_31)
inline_kb5.row(inline_28, inline_6)
inline_kb5.row(inline_44)
inline_kb5.row(inline_36)

inline_kb7 = InlineKeyboardMarkup(row_width=2)
inline_kb7.row(inline_26, inline_21)
inline_kb7.row(inline_17, inline_52)
inline_kb7.row(inline_18, inline_20)
inline_kb7.row(inline_29, inline_55)
inline_kb7.row(inline_27, inline_19)
inline_kb7.row(inline_25, inline_22)
inline_kb7.row(inline_23, inline_24)
inline_kb7.row(inline_53, inline_56)
inline_kb7.row(inline_30, inline_54)
inline_kb7.row(inline_57, inline_28)

inline_kb8 = InlineKeyboardMarkup(row_width=2)
inline_kb8.row(inline_37, inline_26)
inline_kb8.row(inline_9, inline_33)
inline_kb8.row(inline_10, inline_34)
inline_kb8.row(inline_32, inline_29)
inline_kb8.row(inline_38, inline_27)
inline_kb8.row(inline_8, inline_43)
inline_kb8.row(inline_39, inline_4)
inline_kb8.row(inline_35, inline_46)
inline_kb8.row(inline_11, inline_45)
inline_kb8.row(inline_41, inline_7)
inline_kb8.row(inline_47, inline_48)
inline_kb8.row(inline_30, inline_5)
inline_kb8.row(inline_66, inline_12)
inline_kb8.row(inline_31, inline_28)
inline_kb8.row(inline_6, inline_44)
inline_kb8.row(inline_36)

inline_kb9 = InlineKeyboardMarkup(row_width=2)
inline_kb9.row(inline_37, inline_26)
inline_kb9.row(inline_9, inline_33)
inline_kb9.row(inline_10, inline_34)
inline_kb9.row(inline_32, inline_29)
inline_kb9.row(inline_38, inline_27)
inline_kb9.row(inline_8, inline_43)
inline_kb9.row(inline_39, inline_4)
inline_kb9.row(inline_35, inline_46)
inline_kb9.row(inline_11, inline_45)
inline_kb9.row(inline_41, inline_7)
inline_kb9.row(inline_47, inline_48)
inline_kb9.row(inline_30, inline_5)
inline_kb9.row(inline_66, inline_12)
inline_kb9.row(inline_31, inline_28)
inline_kb9.row(inline_6, inline_44)
inline_kb9.row(inline_36)
